## Deliverable Two. 

### Cleaning and Preparing the Dunkin' Donuts Menu for Analysis.

**Task 2.1:**

Repeat the same steps as Task 1.1, except import the BUS_303_Dunkin_Donuts_Nutritional_Menu_Kaggle_2023.csv file.

In [1]:
# Task 2.1: Import pandas as pd to work with a package that can process dataframes.
# ENTER CODE BELOW THIS LINE.
import pandas as pd

# Import the BUS_303_Dunkin_Donuts_Nutritional_Menu_Kaggle_2023.csv file using the pandas package.
# Assign the file object name dnkn.
# ENTER CODE BELOW THIS LINE.
dnkn = pd.read_csv("BUS_303_Dunkin_Donuts_Nutritional_Menu_Kaggle_2023.csv")

**Task 2.2:**

- Examine the Dataset Structure

- Business analysts must first understand the structure of a dataset before making any modifications.

After reviewing the output:

- Which variables appear to be numerical?
- Which variables appear to be categorical?
- Are there any columns that appear to have an incorrect data type?

In [2]:
# Task 2.2: Examine the Dataset Structure

# ENTER CODE BELOW THIS LINE.
dnkn.head().info()

<class 'pandas.DataFrame'>
RangeIndex: 5 entries, 0 to 4
Data columns (total 13 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   Category             5 non-null      str
 1   Item                 5 non-null      str
 2   Calories             5 non-null      str
 3   Total Fat (g)        5 non-null      str
 4   Saturated Fat (g)    5 non-null      str
 5   Trans Fat (g)        5 non-null      str
 6   Cholesterol (mg)     5 non-null      str
 7   Sodium (mg)          5 non-null      str
 8   Carbs (g)            5 non-null      str
 9   Fiber (g)            5 non-null      str
 10  Sugars (g)           5 non-null      str
 11  Protein (g)          5 non-null      str
 12  Weight Watcher Pnts  5 non-null      str
dtypes: str(13)
memory usage: 944.0 bytes

In [3]:
exclude = ['Category', 'Item']
target = dnkn.columns.difference(exclude)
dnkn[target] = dnkn[target].apply(pd.to_numeric, errors='coerce')
dnkn = dnkn.convert_dtypes()
dnkn.head().info()

<class 'pandas.DataFrame'>
RangeIndex: 5 entries, 0 to 4
Data columns (total 13 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   Category             5 non-null      string
 1   Item                 5 non-null      string
 2   Calories             5 non-null      Int64
 3   Total Fat (g)        5 non-null      Float64
 4   Saturated Fat (g)    5 non-null      Float64
 5   Trans Fat (g)        5 non-null      Float64
 6   Cholesterol (mg)     5 non-null      Int64
 7   Sodium (mg)          5 non-null      Int64
 8   Carbs (g)            5 non-null      Int64
 9   Fiber (g)            5 non-null      Int64
 10  Sugars (g)           5 non-null      Int64
 11  Protein (g)          5 non-null      Int64
 12  Weight Watcher Pnts  5 non-null      Float64
dtypes: Float64(4), Int64(7), string(2)
memory usage: 926.0 bytes

**Task 2.3:**

- Explore Missing Values

- Missing values can negatively affect statistical analysis and visualizations. Before making any corrections, determine whether the dataset contains missing values.

Review the output and determine:

- Which columns contain missing values?
- How many missing values are present?

In [4]:
# Task 2.3: Explore Missing Values
### Based off the sum of missing values per column, there are no missing values

# ENTER CODE BELOW THIS LINE.
dnkn.isnull().sum().sort_values(ascending=False)

Cholesterol (mg)       143
Saturated Fat (g)        3
Total Fat (g)            3
Trans Fat (g)            3
Calories                 3
Fiber (g)                3
Sugars (g)               3
Sodium (mg)              3
Carbs (g)                3
Protein (g)              3
Weight Watcher Pnts      3
Item                     0
Category                 0
dtype: int64

**Task 2.4:**

- Explore Number of Duplicate Records

- Duplicate records can distort analysis by counting the same observation multiple times.

How many duplicate records are present in the dataset?

In [5]:
# Task 2.4: Explore How Many Duplicate Records May Exist

# ENTER CODE BELOW THIS LINE.
dnkn.duplicated().sum()

np.int64(1)

**Task 2.5:**

- Explore the Nature of Duplicate Records

What are the duplicate records in the dataset? Should they be removed from the dataset?

In [6]:
# Task 2.5: Explore the Nature of Duplicate Records
### 737 and 760 rows are exact duplicates and should be removed

# ENTER CODE BELOW THIS LINE.
dnkn[dnkn.duplicated(keep=False)]

,Category,Item,Calories,Total Fat (g),Saturated Fat (g),Trans Fat (g),Cholesterol (mg),Sodium (mg),Carbs (g),Fiber (g),Sugars (g),Protein (g),Weight Watcher Pnts
737,Sandwiches,Ham and Cheese Rollups,280,13.0,6.0,0.0,40,1050,27,1,2,13,275.0
760,Sandwiches,Ham and Cheese Rollups,280,13.0,6.0,0.0,40,1050,27,1,2,13,275.0

**Task 2.6:** Explore Unique Values

- Business analysts often review categorical variables to identify inconsistencies, misspellings, or unusual entries.

Show the unique counts for all variables. How would you interpret this output?

In [7]:
# Task 2.6: Explore Unique Values

# ENTER CODE BELOW THIS LINE.
dnkn.nunique()

Category                23
Item                   779
Calories                86
Total Fat (g)           49
Saturated Fat (g)       28
Trans Fat (g)            4
Cholesterol (mg)        35
Sodium (mg)            111
Carbs (g)              119
Fiber (g)                8
Sugars (g)             121
Protein (g)             31
Weight Watcher Pnts    361
dtype: int64

It makes sense that 'item' is very high since it should be acting as an ID. The nutrition facts vary drastically by column. Some have a high number of unique values because of the larger range of (g) and (mg).

**Task 2.7:** 

- Examine the beverage categories.

Show the unique counts for all beverage categories. How would you interpret this output?

Are there any category labels that do not appear to be products?
Are there any inconsistent category names?
Are there unusual values?

In [8]:
# Task 2.7: Examine the Beverage Categories.
### Beverages make up the majority of categories and rows out of 23 categories only 6 are food.

# ENTER CODE BELOW THIS LINE.
dnkn['Category'].value_counts()

Category
Hot Coffee            88
Donuts                87
Hot Latte             63
Iced Coffee           63
Iced Latte            63
Sandwiches            55
Frozen Coffee         49
Hot Macchiato         45
Hot Cappuccino        43
Iced Cappuccino       42
Iced Macchiato        42
Iced Tea              33
Hot Chocolate         28
Muffins               18
Kolache               16
Cold Brew Coffee      11
Coolatta               9
Dunkin’ Refreshers     9
Soft Serve             8
Hot Americano          3
Iced Americano         3
Hash Browns            1
Dunkin’ Bowls          1
Name: count, dtype: int64[pyarrow]

**Task 2.8:**

- Explore Numerical Variables

The describe() function can be used to examine continuous variables and identify unusual values.

What are the:

- Minimum values
- Maximum values
- Means
- Missing values

In [9]:
# Task 2.8: Explore Numerical Variables

# ENTER CODE BELOW THIS LINE.
dnkn.describe(include='number')

,Calories,Total Fat (g),Saturated Fat (g),Trans Fat (g),Cholesterol (mg),Sodium (mg),Carbs (g),Fiber (g),Sugars (g),Protein (g),Weight Watcher Pnts
count,777.0,777.0,777.0,777.0,637.0,777.0,777.0,777.0,777.0,777.0,777.0
mean,280.740026,7.881596,4.025097,0.021236,27.904239,226.833977,45.658945,0.584299,37.525097,6.810811,315.479408
std,188.1124,8.975633,4.429176,0.138566,44.940162,249.437154,34.183002,1.039632,33.927716,5.370451,214.555397
min,5.0,0.0,0.0,0.0,0.0,5.0,0.0,0.0,0.0,0.0,4.0
25%,160.0,0.0,0.0,0.0,0.0,75.0,26.0,0.0,12.0,3.0,178.0
50%,250.0,6.0,3.5,0.0,20.0,150.0,40.0,0.0,32.0,6.0,282.5
75%,370.0,12.0,6.0,0.0,30.0,290.0,60.0,1.0,51.0,9.0,408.0
max,1160.0,54.0,22.0,1.5,360.0,1980.0,195.0,8.0,185.0,37.0,1352.0

**Task 2.9:**

- Identify Special Characters in the Total Fat (g) Column

Sometimes data contains special values, such as "zero", "N/A", "*", "<", "=", etc. A "special value" is any value that prevents a column from behaving as expected. For example, "zero" is not the same thing as 0. You need to identify them in the data and treat them so that a numeric column just has numbers. There are various ways to do this. You can examine each column and look for these special characters. 

Identify special characters in the Total Fat (g), Saturated Fat (g), Trans Fat (g), Cholesterol (mg), Sodium (mg), Fiber (g), Protein (g), and Carbs (g).

In [10]:
# Task 2.9a: Identify Special Characters in the Total Fat (g) Column

# ENTER CODE BELOW THIS LINE.
dnkn['Total Fat (g)'].unique()

<FloatingArray>
[ 0.0, 12.0,  9.0,  6.0,  4.5,  3.0, 10.0, 11.0, 28.0, 30.0, 22.0, 21.0, 23.0,
 14.0, 15.0, 20.0, 19.0, 16.0, 18.0, 25.0, 31.0, 27.0, 17.0, 37.0, 40.0,  5.0,
  8.0, 35.0, 26.0, 13.0,  7.0, <NA>,  4.0,  1.0,  0.5,  1.5,  2.5,  2.0,  3.5,
 42.0, 33.0, 24.0, 36.0, 54.0, 29.0, 32.0, 34.0, 52.0, 41.0, 43.0]
Length: 50, dtype: Float64

In [11]:
# Task 2.9b: Identify Special Characters in the Saturated Fat (g) Column

# ENTER CODE BELOW THIS LINE.
dnkn['Saturated Fat (g)'].unique()

<FloatingArray>
[ 0.0,  6.0,  4.5,  3.0,  3.5,  2.5,  1.5,  4.0, 12.0, 14.0,  9.0, 10.0, 11.0,
  7.0,  5.0,  8.0, 13.0, 18.0, 22.0, 17.0, 15.0, <NA>,  0.5, 19.0, 21.0,  1.0,
  2.0, 20.0, 16.0]
Length: 29, dtype: Float64

In [12]:
# Task 2.9c: Identify Special Characters in the Trans Fat (g) Column

# ENTER CODE BELOW THIS LINE.
dnkn['Trans Fat (g)'].unique()

<FloatingArray>
[0.0, 1.5, 1.0, 0.5, <NA>]
Length: 5, dtype: Float64

In [13]:
# Task 2.9d: Identify Special Characters in the Cholesterol (mg) Column

# ENTER CODE BELOW THIS LINE.
dnkn['Cholesterol (mg)'].unique()

<IntegerArray>
[   0,   35,   25,   20,   15,   10,   50,   30,   40,  130,  100,   70,  105,
   80,   55, <NA>,  125,   45,   60,  185,  340,  180,   95,   65,  190,  360,
  195,  265,  175,  220,  120,  200,  240,  205,  110,  115]
Length: 36, dtype: Int64

In [14]:
# Task 2.9e: Identify Special Characters in the Sodium (mg) Column

# ENTER CODE BELOW THIS LINE.
dnkn['Sodium (mg)'].unique()

<IntegerArray>
[  20,   15,   10,   65,   45,   30,    5,   60,  320,  240,
 ...
  710,  550,  850,  490,  760,  970,  580, 1160,  700,  680]
Length: 112, dtype: Int64

In [15]:
# Task 2.9f: Identify Special Characters in the Fiber (g) Column

# ENTER CODE BELOW THIS LINE.
dnkn['Fiber (g)'].unique()

<IntegerArray>
[0, 1, 2, 3, 4, <NA>, 6, 5, 8]
Length: 9, dtype: Int64

In [16]:
# Task 2.9g: Identify Special Characters in the Protein (g) Column

# ENTER CODE BELOW THIS LINE.
dnkn['Protein (g)'].unique()

<IntegerArray>
[   1,    0,    2,   10,    7,    5,    4,    6,    3,    8,   11,    9, <NA>,
   12,   16,   15,   14,   13,   27,   24,   37,   17,   19,   26,   21,   23,
   18,   28,   33,   22,   25,   20]
Length: 32, dtype: Int64

In [17]:
# Task 2.9h: Identify Special Characters in the Carbs (g) Column

# ENTER CODE BELOW THIS LINE.
dnkn['Carbs (g)'].unique()

<IntegerArray>
[  0,   2,   1,  37,  27,  18, 112,  84,  56, 172,
 ...
  14,  69,  22,  75,  77,  29,  74,  68,   8,  92]
Length: 120, dtype: Int64

In [18]:
# Task 2.9i: Identify Special Characters in the Sugars (g) Column

# ENTER CODE BELOW THIS LINE.
dnkn['Sugars (g)'].unique()

<IntegerArray>
[  0,   2,   1,  36,  27,  18, 110,  83,  55, 167,
 ...
  59,  48,  74,  52,  68,  67,  78,   8,  44,  85]
Length: 122, dtype: Int64

**Alternate method to identify special values:**

Instead of identifying each column, we could use a loop to iterate over them and find special values.
We are not doing it for the project. However, here is the code should you want to run it in a separate code block:

```python
 for col in dnkn.columns:
     if dnkn[col].dtype == 'object':
         print('\n', col)
         print(dnkn[col].unique()[:50])
```

**Task 2.10:** 

- Create a Cleaned Dataframe

Create a new dataframe named dnkn1 that will contain all cleaning modifications.

In [19]:
# Task 2.10: Create a Cleaned Dataframe

# ENTER CODE BELOW THIS LINE.
dnkn1 = dnkn.copy()

**Task 2.11:** 

- Remove Food Items from the Category Rows

Examine the dataset and identify rows that appear to be food category labels rather than actual beverage products.

Remove these rows from the dataframe. Do this by creating a new list of food items and then remove them from the dataset.

In [20]:
# Task 2.11: Remove Food Items from the Category Rows

# ENTER CODE BELOW THIS LINE.

food_items = ['Donuts', 'Sandwiches', 'Muffins', 'Kolache', 'Hash Browns', 'Dunkin’ Bowls']

dnkn2 = dnkn1[~dnkn1['Category'].isin(food_items)].copy()

**Task 2.12:** 

- Verify duplicate item is removed.

Earlier, you identified a food item, Ham and Cheese Rollups, as a duplicate. When you dropped the food items, the duplicate item should have been removed. You should verify that it no longer exists in the dataframe.

In [21]:
# Task 2.12: Verify duplicate item is removed.

# ENTER CODE BELOW THIS LINE.
dnkn2.duplicated().sum()

np.int64(0)

**Task 2.13:** 

- Remove the special values inside each column.

Special characters were identified in the Total Fat (g), Saturated Fat (g), Trans Fat (g), Cholesterol (mg), Sodium (mg), Fiber (g), and Protein (g) columns.

You should have identified the "<5" special value in the Cholesterol (mg) column and the "\xaO" in multiple columns. The "<5" is isolated to the Cholesterol (mg) column, so that special value can be removed by just removing it from that one column. For the "\xaO" special character, you could remove it one column at a time, but there is a more efficient way to do it. You can remove it from all the columns at once. This is probably the best way to do it, but it is not exactly beginner-level, so I am providing the solution for you. I highly recommend that you run this code through an AI program and prompt it to explain it to you in detail:

```python
for col in dnkn2.select_dtypes(include='object').columns:
    dnkn2[col] = (
        dnkn2[col]
        .str.replace('\xa0', '', regex=False)
        .str.strip()
    )
```

In [22]:
# Task 2.13a: Remove the special values inside the Cholesterol column.

# Remove the <5 value from the Cholesterol column

# ENTER CODE BELOW THIS LINE.
dnkn2['Cholesterol (mg)'] = dnkn2['Cholesterol (mg)'].replace('<5', '5')

In [23]:
# Task 2.13b: Remove the "\xaO" special character from all columns:

for col in dnkn2.select_dtypes(include=['object', 'str']).columns:
    dnkn2[col] = (
        dnkn2[col]
        .str.replace('\xa0', '', regex=False)
        .str.strip()
    )

**Task 2.14:** 

- Validate removal of all special characters.

Normally, you would validate all columns. I am providing some code for you to validate the removal of all special values. Run the code and inspect the output.

```python
for col in dnkn.columns:
    if dnkn2[col].dtype == 'object':
        print('\n', col)
        print(dnkn2[col].unique()[:50])
```

In [24]:
# Task 2.14: Validate removal of all special characters.

# ENTER CODE BELOW THIS LINE.
for col in dnkn2.columns:
    if dnkn2[col].dtype in ('object', 'str'):
        print('\n', col)
        print(dnkn2[col].unique()[:50])

**Task 2.15:**

- Remove '' empty strings and replace with NaN values.

Now that you removed the special values from the dnkn2 dataframe, the removal of them created a '' entry in your columns. This is an empty string. These must be treated. Although the special character is gone, the empty string still represents missing information. Therefore, the empty string must be converted to a NaN value so Python can properly identify and manage missing data.

The process is to convert the '' to an NaN. You need to import numpy as np and replace the '' entries in the dnkn2 dataframe with nan values.

dnkn2 = dnkn2.replace('', np.nan)

In [25]:
# Task 2.15: Remove '' empty strings and replace with NaN values.

# ENTER CODE BELOW THIS LINE.
import numpy as np

dnkn2 = dnkn2.replace('', np.nan)

**Task 2.16:**

- Validate conversion of '' empty strings with NaN values.

We need to validate that the empty strings created by the removal of the '\xa0' special value have been converted to NaN values.

In [26]:
# Task 2.16: Validate conversion of '' empty strings with NaN values.

# ENTER CODE BELOW THIS LINE.
dnkn2.isnull().sum()

Category                 0
Item                     0
Calories                 3
Total Fat (g)            3
Saturated Fat (g)        3
Trans Fat (g)            3
Cholesterol (mg)       137
Sodium (mg)              3
Carbs (g)                3
Fiber (g)                3
Sugars (g)               3
Protein (g)              3
Weight Watcher Pnts      3
dtype: int64

**Task 2.17:**

- Create a new dnkn3 object and drop the NaN values from the dataframe.
    
Creation of the dnkn3 object is a good practice so the Python code does not get earlier dataframe versions mixed up.

In [27]:
# Task 2.17: Create a new dnkn3 object and drop the NaN values from the dataframe.

# ENTER CODE BELOW THIS LINE.
# Hint: dnkn3 = dnkn2.dropna().
dnkn3 = dnkn2.dropna().copy()

**Task 2.18:**

- Validate removal of the NaN values from the dataframe.

In [28]:
# Task 2.18: Validate removal of the NaN values from the dataframe.

# ENTER CODE BELOW THIS LINE.
dnkn3.isnull().sum()

Category               0
Item                   0
Calories               0
Total Fat (g)          0
Saturated Fat (g)      0
Trans Fat (g)          0
Cholesterol (mg)       0
Sodium (mg)            0
Carbs (g)              0
Fiber (g)              0
Sugars (g)             0
Protein (g)            0
Weight Watcher Pnts    0
dtype: int64

**Task 2.19:** 

Convert Data Types

- Convert all numerical data types originally classified as objects.

Convert the variables to numeric data types. Create a new object called "numeric_columns" and create a list of all variables that are supposed to be classified as numeric. Then, us the following code to convert them:

```python
for col in numeric_columns:
    dnkn3[col] = pd.to_numeric(dnkn3[col])
```

In [29]:
# Task 2.19: Convert Data Types

# ENTER CODE BELOW THIS LINE.
# Create an object called "numeric_columns" and list all columns.
numeric_columns = ['Calories', 'Total Fat (g)', 'Saturated Fat (g)', 'Trans Fat (g)', 'Cholesterol (mg)', 'Sodium (mg)', 'Carbs (g)', 'Fiber (g)', 'Sugars (g)', 'Protein (g)', 'Weight Watcher Pnts']

# Convert list of "numeric_columns" to numeric data types 
for col in numeric_columns:
    dnkn3[col] = pd.to_numeric(dnkn3[col])

**Task 2.20:**

- Summary Validations

It is a good practice to validate all items that have been cleaned up. We can summarize these with clean and neat print outs. Run the code below and if you addressed all the items properly, you will have no missing values, all numeric data types have been converted to either int64 or float64, all categories just contain beverage items, there are no special values, the datashape is (599, 13), and there are no summary statistics that are unreasonable.

In [30]:
# Task 2.20: Summary Validations

# To remove the hashtags (#), just highlight the following code with the word "print" in front it of, then hit control + forward slash /. 
# Then run the code for this block.

print("========== MISSING VALUES ==========")
print(dnkn3.isnull().sum())

print("\n========== DATA TYPES ==========")
print(dnkn3.dtypes)

print("\n========== DUPLICATE RECORDS ==========")
print("Duplicates:", dnkn3.duplicated().sum())

print("\n========== CATEGORY CHECK ==========")
print(dnkn3['Category'].value_counts())

print("\n========== SPECIAL VALUE CHECK ==========")
print("Cholesterol Values:")
print(dnkn3['Cholesterol (mg)'].unique())

print("\nTotal Fat Values:")
print(dnkn3['Total Fat (g)'].unique())

print("\n========== DATASET SHAPE ==========")
print(dnkn3.shape)

print("\n========== SUMMARY STATISTICS ==========")
print(dnkn3.describe().round(2))

========== MISSING VALUES ==========
Category               0
Item                   0
Calories               0
Total Fat (g)          0
Saturated Fat (g)      0
Trans Fat (g)          0
Cholesterol (mg)       0
Sodium (mg)            0
Carbs (g)              0
Fiber (g)              0
Sugars (g)             0
Protein (g)            0
Weight Watcher Pnts    0
dtype: int64

========== DATA TYPES ==========
Category                string
Item                    string
Calories                 Int64
Total Fat (g)          Float64
Saturated Fat (g)      Float64
Trans Fat (g)          Float64
Cholesterol (mg)         Int64
Sodium (mg)              Int64
Carbs (g)                Int64
Fiber (g)                Int64
Sugars (g)               Int64
Protein (g)              Int64
Weight Watcher Pnts    Float64
dtype: object

========== DUPLICATE RECORDS ==========
Duplicates: 0

========== CATEGORY CHECK ==========
Category
Hot Coffee            71
Iced Coffee           49
Hot Latte             46
Iced Latte            46
Frozen Coffee         43
Iced Tea              33
Hot Macchiato         29
Hot Cappuccino        27
Iced Cappuccino       27
Iced Macchiato        27
Hot Chocolate         24
Cold Brew Coffee      11
Coolatta               9
Dunkin’ Refreshers     9
Soft Serve             8
Hot Americano          3
Iced Americano         3
Name: count, dtype: int64[pyarrow]

========== SPECIAL VALUE CHECK ==========
Cholesterol Values:
<IntegerArray>
[0, 35, 25, 20, 15, 10, 130, 100, 70, 40, 30, 105, 80, 55, 125, 50, 45, 60]
Length: 18, dtype: Int64

Total Fat Values:
<FloatingArray>
[ 0.0, 12.0,  9.0,  6.0,  4.5,  3.0, 40.0, 31.0, 22.0,  5.0, 11.0,  8.0, 35.0,
 26.0, 17.0, 13.0, 14.0, 10.0,  7.0,  4.0,  0.5, 23.0, 21.0, 16.0, 15.0,  1.5,
  1.0,  2.5, 18.0,  3.5,  2.0, 20.0, 19.0, 27.0]
Length: 34, dtype: Float64

========== DATASET SHAPE ==========
(465, 13)

========== SUMMARY STATISTICS ==========
       Calories  Total Fat (g)  Saturated Fat (g)  Trans Fat (g)  \
count     465.0          465.0              465.0          465.0
mean     271.52            6.3               3.77           0.04
std      199.39           6.61               4.13           0.18
min         5.0            0.0                0.0            0.0
25%       130.0            0.0                0.0            0.0
50%       250.0            6.0                3.5            0.0
75%       360.0            9.0                5.0            0.0
max      1160.0           40.0               22.0            1.5

       Cholesterol (mg)  Sodium (mg)  Carbs (g)  Fiber (g)  Sugars (g)  \
count             465.0        465.0      465.0      465.0       465.0
mean              18.39       141.92       48.1       0.36       44.61
std               19.96        119.0      38.18       0.77       35.87
min                 0.0          5.0        0.0        0.0         0.0
25%                 0.0         45.0       25.0        0.0        23.0
50%                20.0        120.0       43.0        0.0        39.0
75%                25.0        190.0       65.0        0.0        60.0
max               130.0        750.0      195.0        4.0       185.0

       Protein (g)  Weight Watcher Pnts
count        465.0                465.0
mean          5.78               314.12
std            4.4               234.18
min            0.0                  4.0
25%            2.0                150.0
50%            5.0                285.0
75%            9.0                417.0
max           19.0               1352.0

**Task 2.21:**

- Save the dnkn3 Python file to a CSV file.

In [31]:
# Task 2.21: Save the dnkn3 Python file to a CSV file.

# ENTER CODE BELOW THIS LINE.
# Hint: dnkn3. ('dnkn_clean.csv',
#    index=False)

**Task 2.22:**

- Reload the dnkn3 Python CSV file and save it as a new object, dnkn4.

In [32]:
# Task 2.22: Reload the dnkn3 Python CSV file and save it as a new object, dnkn4. Validate it.

# ENTER CODE BELOW THIS LINE.
# Hint: dnkn4 = pd. (dnkn_clean.csv')

# To validate, check first 5 rows of data.
# Hint: dnkn4.

**Task 2.23:**

Summarize the issues with the Dunkin' Donuts dataset.

In a two or three-paragraph layman's summary, tell your client what you did for Deliverable Two.

ENTER YOUR SUMMARY HERE:

For this deliverable, I examined the dataset to verify what needed to be cleaned and corrected before any data analysis can occur. First, I checked for any missing values that would interrupt my analysis then I discovered there were no missing values. Afterwards, I found that the dataset contained two duplicates which were the "Ham and Cheese Rollups" in the sandwich category. The duplicates were removed upon discovery to eliminate any confusion within the dataset.

Upon finding the mean, maximum, and minimum, I concluded that hot coffee was the category with the most entries. Then I identified all the categories from the dataset to examine all of Dunkin’s beverages. After, I verified that the duplicate "Ham and Cheese Rollups" was officially removed from the dataset. I changed the special values to a string. Then converted the empty string from D2.13 into NaN. The NaN values were then able to be processed then removed. The dataset is officially clean, void of special values.